[book]
authors = ["sagi21805"]
language = "en"
src = "src"
title = "mdbook-rust-highlight"

[preprocessor.rust-highlight]
whichlang = true
command = "cargo run --release --manifest-path=../Cargo.toml --locked"

[output.html]
additional-css = ["theme/hlrs.css", "theme/whichlang.css"]
additional-js = ["theme/whichlang.js"]
