[book]
authors = ["sagi21805"]
language = "en"
src = "src"
title = "test-book"

[preprocessor.webinclude]
before = ["rust-highlight"]

[preprocessor.rust-highlight]
whichlang = false
command = "cargo run --release --locked"

[output.html]
additional-css = ["theme/hlrs.css", "theme/whichlang.css"]
additional-js = ["theme/whichlang.js"]
